<a href="https://colab.research.google.com/github/codesfromvikrant/data-analytics-learning/blob/learning/Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

Pandas --- Data Analysis(EDA), Data Manipulations, Data Cleaning(Pre Processing)

A DataFrame is a labeled 2-dimensional data structure used to store and manipulate tabular data — basically a programmable table.
DataFrame is a specialized version of Dictionary DataStructure in python.

In [3]:
# Creating Empty Dataframes
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [5]:
# Creating Dataframes from the list

lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [7]:
# Creating Dataframes from numpy array list

data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }
df = pd.DataFrame(data)
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
# Creating dataframes from python dictionaries

data = [{
    'a': 1,
    'b': 2
}, {
    'a': 5,
    'b': 10,
    'c': 20
}]
df = pd.DataFrame(data)
print(df)

data = {'Name': ['Jake', 'Eve', 'Charlie'],
        'Age': [ 22, 35, 28],
        'Gender': [ 'Male', 'Female', 'Male'],
        'Salary': [40000, 70000, 48000]}
df = pd.DataFrame(data)
print(df)

# Setting new index
res = df.set_index('Name')

# resetting index
res = df.reset_index(drop=True)
print(res)

   a   b     c
0  1   2   NaN
1  5  10  20.0
      Name  Age  Gender  Salary
0     Jake   22    Male   40000
1      Eve   35  Female   70000
2  Charlie   28    Male   48000
      Name  Age  Gender  Salary
0     Jake   22    Male   40000
1      Eve   35  Female   70000
2  Charlie   28    Male   48000

### Indexing with loc
##### allows to access the rows and columns of the dataframe using their labels

In [20]:
data = {'age': [25, 30], 'city': ['NY', 'LA']}
df = pd.DataFrame(data, index=['Alice', 'Bob'])
row = df.loc['Alice']
print(df)
print("")
print(row)

       age city
Alice   25   NY
Bob     30   LA

age     25
city    NY
Name: Alice, dtype: object

### set_index()
##### setting the column as the index instead of using the default index 0,1,2,3......

In [21]:
data = {
    "ID": [101, 102, 103],
    "Name": ["Rahul", "Amit", "Vikram"],
    "Age": [25, 30, 28]
}

df = pd.DataFrame(data)
print(df)

df = df.set_index("ID")
print(df)

    ID    Name  Age
0  101   Rahul   25
1  102    Amit   30
2  103  Vikram   28
       Name  Age
ID
101   Rahul   25
102    Amit   30
103  Vikram   28

### setting up multi index

In [24]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR"],
    "Employee_ID": [101, 102, 103],
    "Name": ["Rahul", "Amit", "Vikram"]
})

df.set_index(["Department", "Employee_ID"], inplace=True)
print(df)

                          Name
Department Employee_ID
IT         101           Rahul
           102            Amit
HR         103          Vikram

In [25]:
## resetting the index to default

df.reset_index(inplace=True)
print(df)

  Department  Employee_ID    Name
0         IT          101   Rahul
1         IT          102    Amit
2         HR          103  Vikram

### indexing with loc
##### loc[] is used to access rows and columns of a DataFrame using their labels (index names and column names).

In [34]:
# Accessing a single row
print(df.loc[0])
print("")

# Accessing multiple rows
print(df.loc[[0, 2]])
print("")

# Accessing a single specific element
print(df.loc[0, 'Department'])
print("")

# Slicing Rows with the loc
print(df.loc[0:2])
print("")

# Filtering rows with the condition
print(df.loc[df['Department'] == "IT"])

Department        IT
Employee_ID      101
Name           Rahul
Name: 0, dtype: object

  Department  Employee_ID    Name
0         IT          101   Rahul
2         HR          103  Vikram

IT

  Department  Employee_ID    Name
0         IT          101   Rahul
1         IT          102    Amit
2         HR          103  Vikram

  Department  Employee_ID   Name
0         IT          101  Rahul
1         IT          102   Amit

### indexing with iloc

In [ ]:
# Creating Dataframes
df = pd.read_csv('sample_data/california_housing_test.csv')

# head -- for first five rows which is default,
df.head()

# tail -- for last five rows
df.tail(n=8) # n=8 argument to get the last 8 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Shape
df.shape

(3000, 9)

In [ ]:
df.columns # to retrive the labels of columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df.keys() # to retrive the labels of columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df['longitude'] # to retrive a specific column

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [ ]:
type(df['longitude']) # this datatype is known as series
# series are homogenous arrays like the array in numpy but this array have labels.

pandas.core.series.Series

In [ ]:
df.info() # to retrieve the basic initial information of your dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df.describe(include='all') # Pandas method used to get a statistical summary of your DataFrame.

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [ ]:
lst_of_keys = ['longitude', 'latitude']
df[lst_of_keys]

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

In [ ]:
# Renaming the Labels in the original dataframe with inplace = True
# inplace = False creates the copy after renaming

data_frame = df.rename(columns={'longitude':'long', 'latitudea':'lat'},)
print(data_frame)
df.head()

        long  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0
...      ...       ...                 ...          ...             ...
2995 -119.86     34.42                23.0       1450.0           642.0
2996 -118.14     34.06                27.0       5257.0          1082.0
2997 -119.70     36.30                10.0        956.0           201.0
2998 -117.12     34.10                40.0         96.0            14.0
2999 -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
df.rename({'seven': '7'}, axis=1, inplace=True) # axis = 1 is the column and axis = 0 is the rows
# You can rename the column label as well as rows label also.

# Changing all the columns to the new ones
# df.columns = ['A', 'B', 'C', 'D', 'e']

In [ ]:
# df.drop() removes rows and columns from the dataframe
df.drop("Age", axis=1)
df.drop(["Age", "Salary"], axis=1)
df.drop(2, axis=0)
df.drop([2, 3], axis=0, inplace=False) # inplace True make the changes in the original data frame while False create a duplicate data

KeyError: "['Age'] not found in axis"

In [ ]:
df['new'] = df['seven']+df['zero'] #creating new column with the operations on the current column in dataset

df.head()

# Working With Rows

In [ ]:
df.head()
el = df['zero']
el

0       0
1       0
2       0
3       0
4       0
       ..
9994    0
9995    0
9996    0
9997    0
9998    0
Name: zero, Length: 9999, dtype: int64

In [ ]:
el[5]

np.int64(0)

In [ ]:
el[5:10]

5    0
6    0
7    0
8    0
9    0
Name: zero, dtype: int64

In [ ]:
# Crated own series
data = pd.Series(['a','b','c','d'], index=[1,5,3,4])
data

1    a
5    b
3    c
4    d
dtype: object

In [ ]:
data[1] # explicit indexing

'a'

In [ ]:
data[1:3] # implicit indexing

5    b
3    c
dtype: object

## **loc and iloc**
### loc for explicit indexing and iloc for implicit indexing
#### loc --> local based indexing
#### iloc ---> positional based indexing

In [ ]:
temp = df.set_index('zero') # setting a complete column values as the index of the row
temp

,7,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
zero,,,,,,,,,,,,,,,,,,,,,
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
temp.loc[0]

,7,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
zero,,,,,,,,,,,,,,,,,,,,,
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
temp.reset_index() # set the index back to the original

# **Work With Rows and Columns**

In [ ]:
df.iloc[2:5,1:3]

   zero  0.1
2     0    0
3     0    0
4     0    0

In [ ]:
df.iloc[1:100:10, 1:4]

    zero  0.1  0.2
1      0    0    0
11     0    0    0
21     0    0    0
31     0    0    0
41     0    0    0
51     0    0    0
61     0    0    0
71     0    0    0
81     0    0    0
91     0    0    0

In [ ]:
df.iloc[-500::-1,2:5]

# **Creating Dataframe from scratch**

In [ ]:
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9], columns=['a','b','c']])

# Concatenate

In [ ]:
df1 = pd.DataFrame({
    'a': [122.0, 118.0],
    'b': [0, 0],
    'c': [23, 54]
})


df2 = pd.DataFrame({
    'a': [-122.0, -118.0],
    'b': [234, 564]
})

concatenated_df = pd.concat([df1, df2], ignore_index=True, axis=1)
print(concatenated_df.tail())

       0  1   2      3    4
0  122.0  0  23 -122.0  234
1  118.0  0  54 -118.0  564

# Merging
##### pd.merge()
##### similar as inner join in sql

In [ ]:
users = pd.DataFrame({'userid':[1,2,3], 'name':['A','B','C']})
msgs = pd.DataFrame({'userid':[1,1,2], 'msg':['hello', 'bye', 'hi']})

# must have one common column like here is userid
pd.merge(users, msgs, on='userid')

   userid name    msg
0       1    A  hello
1       1    A    bye
2       2    B     hi